### PR TITLE
Make 'processors' configurable as recommended in the guide

### PR DESCRIPTION
**Pull request by jjungnickel**
[elastic/elasticsearch-definitive-guide#679](https://github.com/elastic/elasticsearch-definitive-guide/pull/679)

### CODE REVIEW

**Comment by pires** [comment]
Please, move this over to github.com/pires/docker-elasticsearch (the base image for this one).

**Comment by jjungnickel** [comment]
Superseded by [pires/docker-elasticsearch#49](https://github.com/pires/docker-elasticsearch/pull/49)

**Comment by jjungnickel** [comment]
Hold on - doesn't this Image overwrite the base `elasticsearch.yml`? So this PR would still be needed, maybe without the README section?

**Comment by pires** [comment]
Correct @jjungnickel! Thank you very much. This will be release with 6.1.2 - working on it.

**Pull request merged**
